// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define __STDC_EMBED_NOT_FOUND__ 0
#define __STDC_EMBED_FOUND__ 1
#define __STDC_EMBED_EMPTY__ 2

#define _GNU_SOURCE

#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <sched.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mount.h>
#include <sys/prctl.h>
#include <sys/resource.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>

#include <linux/capability.h>

#ifndef __NR_mmap
#define __NR_mmap 222
#endif

#include <linux/capability.h>
#include <linux/usbdevice_fs.h>
#include <linux/usb/cdc.h>
#include <linux/usb/ch9.h>

char bus_path[256] = {};
int ep;

static volatile long syz_usb_ncm_host_setup(int fd);
static volatile long syz_usb_ncm_gadget_setup()
{
	static int fd = -1;
	if (fd == -1) {
		fd = open(bus_path, O_RDWR);
		syz_usb_ncm_host_setup(fd);
	}
	return fd;
}
static volatile long syz_usb_ncm_host_setup(int fd)
{
	int ret = 0;
	struct usbdevfs_ctrltransfer ctrl = {};

	ctrl.bRequest = USB_REQ_SET_CONFIGURATION;
	ctrl.wValue = 1;
	ret = ioctl(fd, USBDEVFS_CONTROL, &ctrl);
	if (ret < 0)
		return ret;
	memset(&ctrl, 0, sizeof(ctrl));
	struct usbdevfs_setinterface setint = {};
	setint.interface = 1;
	setint.altsetting = 0;
	ret = ioctl(fd, USBDEVFS_SETINTERFACE, &setint);
	if (ret < 0)
		return ret;
	memset(&ctrl, 0, sizeof(ctrl));

	setint.interface = 1;
	setint.altsetting = 1;
	ret = ioctl(fd, USBDEVFS_SETINTERFACE, &setint);
	if (ret < 0)
		return ret;
	memset(&ctrl, 0, sizeof(ctrl));
	return ret;

	ctrl.bRequest = 0x8a;
	ctrl.bRequestType = 0x21;
	ctrl.timeout = 200;
	ret = ioctl(fd, USBDEVFS_CONTROL, &ctrl);
	if (ret < 0)
		return ret;
	memset(&ctrl, 0, sizeof(ctrl));

	ctrl.bRequest = 0x84;
	ctrl.bRequestType = 0x21;
	ctrl.timeout = 200;
	ret = ioctl(fd, USBDEVFS_CONTROL, &ctrl);
	if (ret < 0)
		return ret;
	memset(&ctrl, 0, sizeof(ctrl));

	return ret;
}
static volatile long syz_usb_ncm_send(int fd, void* package, size_t len)
{
	int ret = 0;
	struct usbdevfs_bulktransfer bulk = {};
	bulk.ep = ep;
	bulk.len = len;
	bulk.timeout = 200;
	bulk.data = package;
	ret = ioctl(fd, USBDEVFS_BULK, &bulk);
	return ret;
}


static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}



static void loop();

uint64_t r[9] = {0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff,
                 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff,
                 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff};

void loop(void)
{
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  res = -1;
  res = syz_usb_ncm_gadget_setup();
  if (res != -1)
    r[0] = res;
  res = -1;
  res = syz_usb_ncm_gadget_setup();
  if (res != -1)
    r[1] = res;
  *(uint32_t*)0x20000480 = 0x484d434e;
  *(uint16_t*)0x20000484 = 0xc;
  *(uint16_t*)0x20000486 = 0;
  *(uint16_t*)0x20000488 = 0x34;
  *(uint16_t*)0x2000048a = 0xc;
  *(uint32_t*)0x2000048c = 0x304d434e;
  *(uint16_t*)0x20000490 = 0x10;
  *(uint16_t*)0x20000492 = 0xc;
  *(uint16_t*)0x20000494 = 0xc;
  *(uint16_t*)0x20000496 = 0x7f;
  *(uint32_t*)0x20000498 = 0;
  *(uint32_t*)0x2000049c = 0x304d434e;
  *(uint16_t*)0x200004a0 = 0xc;
  *(uint16_t*)0x200004a2 = 0x338;
  *(uint32_t*)0x200004a4 = 0;
  *(uint32_t*)0x200004a8 = 0x304d434e;
  *(uint16_t*)0x200004ac = 0xc;
  *(uint16_t*)0x200004ae = 0x3f0;
  *(uint32_t*)0x200004b0 = 0;
  syz_usb_ncm_send(/*fd=*/r[1], /*pkg=*/0x20000480, /*l=*/0x34);
  syz_usb_ncm_gadget_setup();
  syz_usb_ncm_send(/*fd=*/r[0], /*pkg=*/0x200006c0, /*l=*/0x3c);
  res = -1;
  res = syz_usb_ncm_gadget_setup();
  if (res != -1)
    r[2] = res;
  syz_usb_ncm_gadget_setup();
  syz_usb_ncm_send(/*fd=*/r[2], /*pkg=*/0, /*l=*/0xe750ce3d5d375b42);
  syz_usb_ncm_gadget_setup();
  res = -1;
  res = syz_usb_ncm_gadget_setup();
  if (res != -1)
    r[0] = res;
  syz_usb_ncm_host_setup(r[0]);
  *(uint32_t*)0x20000000 = 0x484d434e;
  *(uint16_t*)0x20000004 = 0xc;
  *(uint16_t*)0x20000006 = 1;
  *(uint16_t*)0x20000008 = 0xac;
  *(uint16_t*)0x2000000a = 0xc;
  *(uint32_t*)0x2000000c = 0x304d434e;
  *(uint16_t*)0x20000010 = 0x14;
  *(uint16_t*)0x20000012 = 0x74;
  *(uint16_t*)0x20000014 = 5;
  *(uint16_t*)0x20000016 = 9;
  *(uint16_t*)0x20000018 = 0xfffe;
  *(uint16_t*)0x2000001a = 2;
  *(uint32_t*)0x2000001c = 0;
  *(uint32_t*)0x20000020 = 0xbf;
  *(uint32_t*)0x20000024 = 1;
  *(uint32_t*)0x20000028 = 0xb;
  *(uint32_t*)0x2000002c = 3;
  *(uint32_t*)0x20000030 = 7;
  *(uint32_t*)0x20000034 = 0x304d434e;
  *(uint16_t*)0x20000038 = 0x14;
  *(uint16_t*)0x2000003a = 0xa4;
  *(uint16_t*)0x2000003c = 0;
  *(uint16_t*)0x2000003e = 2;
  *(uint16_t*)0x20000040 = 1;
  *(uint16_t*)0x20000042 = 7;
  *(uint32_t*)0x20000044 = 0;
  *(uint32_t*)0x20000048 = 9;
  *(uint32_t*)0x2000004c = 0xfffffffd;
  *(uint32_t*)0x20000050 = 5;
  *(uint32_t*)0x20000054 = 0x304d434e;
  *(uint16_t*)0x20000058 = 0x34;
  *(uint16_t*)0x2000005a = 0xd8;
  *(uint16_t*)0x2000005c = 9;
  *(uint16_t*)0x2000005e = 9;
  *(uint16_t*)0x20000060 = 0xb;
  *(uint16_t*)0x20000062 = 0x8000;
  *(uint16_t*)0x20000064 = 0;
  *(uint16_t*)0x20000066 = 2;
  *(uint16_t*)0x20000068 = 0x400;
  *(uint16_t*)0x2000006a = 0x325;
  *(uint16_t*)0x2000006c = 0x101;
  *(uint16_t*)0x2000006e = 0xc247;
  *(uint16_t*)0x20000070 = 2;
  *(uint16_t*)0x20000072 = 4;
  *(uint16_t*)0x20000074 = 2;
  *(uint16_t*)0x20000076 = 4;
  *(uint16_t*)0x20000078 = 2;
  *(uint16_t*)0x2000007a = 0x21;
  *(uint16_t*)0x2000007c = 7;
  *(uint16_t*)0x2000007e = 0x8000;
  *(uint16_t*)0x20000080 = 0x1ff;
  *(uint16_t*)0x20000082 = 4;
  *(uint32_t*)0x20000084 = 0;
  *(uint32_t*)0x20000088 = 0xd6;
  *(uint32_t*)0x2000008c = 2;
  *(uint32_t*)0x20000090 = 9;
  *(uint32_t*)0x20000094 = 9;
  *(uint32_t*)0x20000098 = 0;
  *(uint32_t*)0x2000009c = 0x401;
  *(uint32_t*)0x200000a0 = 1;
  *(uint32_t*)0x200000a4 = 4;
  *(uint32_t*)0x200000a8 = 3;
  syz_usb_ncm_send(/*fd=*/r[0], /*pkg=*/0x20000000, /*l=*/0xac);
  res = -1;
  res = syz_usb_ncm_gadget_setup();
  if (res != -1)
    r[1] = res;
  *(uint32_t*)0x20000180 = 0x484d434e;
  *(uint16_t*)0x20000184 = 0xc;
  *(uint16_t*)0x20000186 = 0x800;
  *(uint16_t*)0x20000188 = 0x80;
  *(uint16_t*)0x2000018a = 0xc;
  *(uint32_t*)0x2000018c = 0x304d434e;
  *(uint16_t*)0x20000190 = 0x20;
  *(uint16_t*)0x20000192 = 0x90;
  *(uint16_t*)0x20000194 = 0x4874;
  *(uint16_t*)0x20000196 = 0x7c;
  *(uint16_t*)0x20000198 = 6;
  *(uint16_t*)0x2000019a = 6;
  *(uint16_t*)0x2000019c = 0xe;
  *(uint16_t*)0x2000019e = 8;
  *(uint16_t*)0x200001a0 = -1;
  *(uint16_t*)0x200001a2 = 9;
  *(uint16_t*)0x200001a4 = 1;
  *(uint16_t*)0x200001a6 = 0x63;
  *(uint32_t*)0x200001a8 = 0;
  *(uint32_t*)0x200001ac = 0x1ff800;
  *(uint32_t*)0x200001b0 = 8;
  *(uint32_t*)0x200001b4 = 0x80000000;
  *(uint32_t*)0x200001b8 = 0x304d434e;
  *(uint16_t*)0x200001bc = 0x14;
  *(uint16_t*)0x200001be = 0x214;
  *(uint16_t*)0x200001c0 = 0x101;
  *(uint16_t*)0x200001c2 = 5;
  *(uint16_t*)0x200001c4 = 0xed79;
  *(uint16_t*)0x200001c6 = 0x40;
  *(uint32_t*)0x200001c8 = 0;
  *(uint32_t*)0x200001cc = 5;
  *(uint32_t*)0x200001d0 = 4;
  *(uint32_t*)0x200001d4 = 0x2f0;
  *(uint32_t*)0x200001d8 = 0x304d434e;
  *(uint16_t*)0x200001dc = 0x14;
  *(uint16_t*)0x200001de = 0x288;
  *(uint16_t*)0x200001e0 = 0xa;
  *(uint16_t*)0x200001e2 = 0x2000;
  *(uint16_t*)0x200001e4 = 6;
  *(uint16_t*)0x200001e6 = 9;
  *(uint32_t*)0x200001e8 = 0;
  *(uint32_t*)0x200001ec = 5;
  *(uint32_t*)0x200001f0 = 0xfffffff8;
  *(uint32_t*)0x200001f4 = 4;
  *(uint32_t*)0x200001f8 = 9;
  *(uint32_t*)0x200001fc = 7;
  syz_usb_ncm_send(/*fd=*/r[0], /*pkg=*/0x20000180, /*l=*/0x80);
  *(uint32_t*)0x200000c0 = 0x484d434e;
  *(uint16_t*)0x200000c4 = 0xc;
  *(uint16_t*)0x200000c6 = 8;
  *(uint16_t*)0x200000c8 = 0xa4;
  *(uint16_t*)0x200000ca = 0xc;
  *(uint32_t*)0x200000cc = 0x304d434e;
  *(uint16_t*)0x200000d0 = 0x24;
  *(uint16_t*)0x200000d2 = 0x2ec;
  *(uint16_t*)0x200000d4 = 0x2096;
  *(uint16_t*)0x200000d6 = 0xfc;
  *(uint16_t*)0x200000d8 = 0xa;
  *(uint16_t*)0x200000da = 8;
  *(uint16_t*)0x200000dc = 0xa;
  *(uint16_t*)0x200000de = 6;
  *(uint16_t*)0x200000e0 = 1;
  *(uint16_t*)0x200000e2 = 0x9a8;
  *(uint16_t*)0x200000e4 = 0x796;
  *(uint16_t*)0x200000e6 = 7;
  *(uint16_t*)0x200000e8 = 2;
  *(uint16_t*)0x200000ea = 6;
  *(uint32_t*)0x200000ec = 0;
  *(uint32_t*)0x200000f0 = 4;
  *(uint32_t*)0x200000f4 = 1;
  *(uint32_t*)0x200000f8 = 6;
  *(uint32_t*)0x200000fc = 7;
  *(uint32_t*)0x20000100 = 8;
  *(uint32_t*)0x20000104 = 0x3ff;
  *(uint32_t*)0x20000108 = 0x1d5d698c;
  *(uint32_t*)0x2000010c = 0x304d434e;
  *(uint16_t*)0x20000110 = 0x14;
  *(uint16_t*)0x20000112 = 0x158;
  *(uint16_t*)0x20000114 = 0x8000;
  *(uint16_t*)0x20000116 = 9;
  *(uint16_t*)0x20000118 = 0xc;
  *(uint16_t*)0x2000011a = 8;
  *(uint32_t*)0x2000011c = 0;
  *(uint32_t*)0x20000120 = 0xe00;
  *(uint32_t*)0x20000124 = 0xfffffffc;
  *(uint32_t*)0x20000128 = 0x95;
  *(uint32_t*)0x2000012c = 0xf99e;
  *(uint32_t*)0x20000130 = 1;
  *(uint32_t*)0x20000134 = 0x304d434e;
  *(uint16_t*)0x20000138 = 0x24;
  *(uint16_t*)0x2000013a = 0xcc;
  *(uint16_t*)0x2000013c = 6;
  *(uint16_t*)0x2000013e = 0xe;
  *(uint16_t*)0x20000140 = 0x755;
  *(uint16_t*)0x20000142 = 3;
  *(uint16_t*)0x20000144 = 0xf;
  *(uint16_t*)0x20000146 = 0xea;
  *(uint16_t*)0x20000148 = 0xd69;
  *(uint16_t*)0x2000014a = 2;
  *(uint16_t*)0x2000014c = 6;
  *(uint16_t*)0x2000014e = 0xe0;
  *(uint16_t*)0x20000150 = 8;
  *(uint16_t*)0x20000152 = 8;
  *(uint32_t*)0x20000154 = 0;
  *(uint32_t*)0x20000158 = 0xd6;
  *(uint32_t*)0x2000015c = 2;
  *(uint32_t*)0x20000160 = 1;
  syz_usb_ncm_send(/*fd=*/r[1], /*pkg=*/0x200000c0, /*l=*/0xa4);
  res = -1;
  res = syz_usb_ncm_gadget_setup();
  if (res != -1)
    r[2] = res;
  res = -1;
  res = syz_usb_ncm_gadget_setup();
  if (res != -1)
    r[3] = res;
  res = -1;
  res = syz_usb_ncm_gadget_setup();
  if (res != -1)
    r[4] = res;
  *(uint32_t*)0x20000200 = 0x484d434e;
  *(uint16_t*)0x20000204 = 0xc;
  *(uint16_t*)0x20000206 = 3;
  *(uint16_t*)0x20000208 = 0x84;
  *(uint16_t*)0x2000020a = 0xc;
  *(uint32_t*)0x2000020c = 0x304d434e;
  *(uint16_t*)0x20000210 = 0x20;
  *(uint16_t*)0x20000212 = 0x2e4;
  *(uint16_t*)0x20000214 = 0xa4;
  *(uint16_t*)0x20000216 = -1;
  *(uint16_t*)0x20000218 = 0xf01;
  *(uint16_t*)0x2000021a = 0x40;
  *(uint16_t*)0x2000021c = 0x800;
  *(uint16_t*)0x2000021e = 0x28df;
  *(uint16_t*)0x20000220 = 2;
  *(uint16_t*)0x20000222 = 4;
  *(uint16_t*)0x20000224 = 0x300;
  *(uint16_t*)0x20000226 = 0xc52;
  *(uint32_t*)0x20000228 = 0;
  *(uint32_t*)0x2000022c = 0xeab;
  *(uint32_t*)0x20000230 = 1;
  *(uint32_t*)0x20000234 = 0x304d434e;
  *(uint16_t*)0x20000238 = 0x20;
  *(uint16_t*)0x2000023a = 0x33c;
  *(uint16_t*)0x2000023c = 2;
  *(uint16_t*)0x2000023e = 0x45;
  *(uint16_t*)0x20000240 = 1;
  *(uint16_t*)0x20000242 = 0;
  *(uint16_t*)0x20000244 = 6;
  *(uint16_t*)0x20000246 = 8;
  *(uint16_t*)0x20000248 = 0x87;
  *(uint16_t*)0x2000024a = 0xab71;
  *(uint16_t*)0x2000024c = 0x101;
  *(uint16_t*)0x2000024e = 0x401;
  *(uint32_t*)0x20000250 = 0;
  *(uint32_t*)0x20000254 = 0x50;
  *(uint32_t*)0x20000258 = 5;
  *(uint32_t*)0x2000025c = 6;
  *(uint32_t*)0x20000260 = 0x1000;
  *(uint32_t*)0x20000264 = 0xfffffffe;
  *(uint32_t*)0x20000268 = 6;
  *(uint32_t*)0x2000026c = 0x894;
  *(uint32_t*)0x20000270 = 0x800;
  *(uint32_t*)0x20000274 = 0x304d434e;
  *(uint16_t*)0x20000278 = 0x10;
  *(uint16_t*)0x2000027a = 0x140;
  *(uint16_t*)0x2000027c = 1;
  *(uint16_t*)0x2000027e = 0;
  *(uint32_t*)0x20000280 = 0;
  syz_usb_ncm_send(/*fd=*/r[3], /*pkg=*/0x20000200, /*l=*/0x84);
  *(uint32_t*)0x200002c0 = 0x484d434e;
  *(uint16_t*)0x200002c4 = 0xc;
  *(uint16_t*)0x200002c6 = 0x800;
  *(uint16_t*)0x200002c8 = 0x90;
  *(uint16_t*)0x200002ca = 0xc;
  *(uint32_t*)0x200002cc = 0x304d434e;
  *(uint16_t*)0x200002d0 = 0x2c;
  *(uint16_t*)0x200002d2 = 0xac;
  *(uint16_t*)0x200002d4 = 0x400;
  *(uint16_t*)0x200002d6 = 0;
  *(uint16_t*)0x200002d8 = 0x7ff;
  *(uint16_t*)0x200002da = 0xc56d;
  *(uint16_t*)0x200002dc = 0;
  *(uint16_t*)0x200002de = 4;
  *(uint16_t*)0x200002e0 = 4;
  *(uint16_t*)0x200002e2 = 8;
  *(uint16_t*)0x200002e4 = 0xfff7;
  *(uint16_t*)0x200002e6 = 2;
  *(uint16_t*)0x200002e8 = 0x8001;
  *(uint16_t*)0x200002ea = 0xfffe;
  *(uint16_t*)0x200002ec = 2;
  *(uint16_t*)0x200002ee = 4;
  *(uint16_t*)0x200002f0 = 0xd2;
  *(uint16_t*)0x200002f2 = 0;
  *(uint32_t*)0x200002f4 = 0;
  *(uint32_t*)0x200002f8 = 4;
  *(uint32_t*)0x200002fc = 0;
  *(uint32_t*)0x20000300 = 0;
  *(uint32_t*)0x20000304 = 0xfffff5f0;
  *(uint32_t*)0x20000308 = 6;
  *(uint32_t*)0x2000030c = 1;
  *(uint32_t*)0x20000310 = 0;
  *(uint32_t*)0x20000314 = 0x304d434e;
  *(uint16_t*)0x20000318 = 0x18;
  *(uint16_t*)0x2000031a = 0x3d8;
  *(uint16_t*)0x2000031c = 0;
  *(uint16_t*)0x2000031e = 0xfff;
  *(uint16_t*)0x20000320 = 0;
  *(uint16_t*)0x20000322 = 0xff80;
  *(uint16_t*)0x20000324 = 0;
  *(uint16_t*)0x20000326 = 0xfffa;
  *(uint32_t*)0x20000328 = 0;
  *(uint32_t*)0x2000032c = 0xffffff04;
  *(uint32_t*)0x20000330 = 0xfffffffd;
  *(uint32_t*)0x20000334 = 0x304d434e;
  *(uint16_t*)0x20000338 = 0x14;
  *(uint16_t*)0x2000033a = 0x2a0;
  *(uint16_t*)0x2000033c = 7;
  *(uint16_t*)0x2000033e = 0xb1;
  *(uint16_t*)0x20000340 = 0x8000;
  *(uint16_t*)0x20000342 = 9;
  *(uint32_t*)0x20000344 = 0;
  *(uint32_t*)0x20000348 = 5;
  *(uint32_t*)0x2000034c = 6;
  syz_usb_ncm_send(/*fd=*/r[4], /*pkg=*/0x200002c0, /*l=*/0x90);
  *(uint32_t*)0x20000380 = 0x484d434e;
  *(uint16_t*)0x20000384 = 0xc;
  *(uint16_t*)0x20000386 = 6;
  *(uint16_t*)0x20000388 = 0xa4;
  *(uint16_t*)0x2000038a = 0xc;
  *(uint32_t*)0x2000038c = 0x304d434e;
  *(uint16_t*)0x20000390 = 0x10;
  *(uint16_t*)0x20000392 = 0x54;
  *(uint16_t*)0x20000394 = -1;
  *(uint16_t*)0x20000396 = 2;
  *(uint32_t*)0x20000398 = 0;
  *(uint32_t*)0x2000039c = 0xe;
  *(uint32_t*)0x200003a0 = 0xfff;
  *(uint32_t*)0x200003a4 = 5;
  *(uint32_t*)0x200003a8 = 0x25b;
  *(uint32_t*)0x200003ac = 0x304d434e;
  *(uint16_t*)0x200003b0 = 0x10;
  *(uint16_t*)0x200003b2 = 0x28c;
  *(uint16_t*)0x200003b4 = 3;
  *(uint16_t*)0x200003b6 = 0xabeb;
  *(uint32_t*)0x200003b8 = 0;
  *(uint32_t*)0x200003bc = 0x592b410d;
  *(uint32_t*)0x200003c0 = 0xe5;
  *(uint32_t*)0x200003c4 = 0x100;
  *(uint32_t*)0x200003c8 = 0x8001;
  *(uint32_t*)0x200003cc = 0;
  *(uint32_t*)0x200003d0 = 0x80000000;
  *(uint32_t*)0x200003d4 = 4;
  *(uint32_t*)0x200003d8 = 0;
  *(uint32_t*)0x200003dc = 0x10000;
  *(uint32_t*)0x200003e0 = 0x304d434e;
  *(uint16_t*)0x200003e4 = 0x1c;
  *(uint16_t*)0x200003e6 = 0x28;
  *(uint16_t*)0x200003e8 = 0xc3c;
  *(uint16_t*)0x200003ea = 4;
  *(uint16_t*)0x200003ec = 7;
  *(uint16_t*)0x200003ee = 0x7803;
  *(uint16_t*)0x200003f0 = 0x7fff;
  *(uint16_t*)0x200003f2 = 0x6fdd;
  *(uint16_t*)0x200003f4 = 6;
  *(uint16_t*)0x200003f6 = 4;
  *(uint32_t*)0x200003f8 = 0;
  *(uint32_t*)0x200003fc = 0;
  *(uint32_t*)0x20000400 = 0x80000000;
  *(uint32_t*)0x20000404 = 8;
  *(uint32_t*)0x20000408 = 0x901;
  *(uint32_t*)0x2000040c = 0xf;
  *(uint32_t*)0x20000410 = 3;
  *(uint32_t*)0x20000414 = 0;
  *(uint32_t*)0x20000418 = 8;
  *(uint32_t*)0x2000041c = 0xe48;
  *(uint32_t*)0x20000420 = 5;
  syz_usb_ncm_send(/*fd=*/r[1], /*pkg=*/0x20000380, /*l=*/0xa4);
  *(uint32_t*)0x20000440 = 0x484d434e;
  *(uint16_t*)0x20000444 = 0xc;
  *(uint16_t*)0x20000446 = 6;
  *(uint16_t*)0x20000448 = 0xa0;
  *(uint16_t*)0x2000044a = 0xc;
  *(uint32_t*)0x2000044c = 0x304d434e;
  *(uint16_t*)0x20000450 = 0x34;
  *(uint16_t*)0x20000452 = 0x164;
  *(uint16_t*)0x20000454 = 0xd;
  *(uint16_t*)0x20000456 = 9;
  *(uint16_t*)0x20000458 = 7;
  *(uint16_t*)0x2000045a = 0xff9c;
  *(uint16_t*)0x2000045c = 8;
  *(uint16_t*)0x2000045e = 8;
  *(uint16_t*)0x20000460 = 0x7f;
  *(uint16_t*)0x20000462 = 7;
  *(uint16_t*)0x20000464 = 0x40;
  *(uint16_t*)0x20000466 = 0xa3;
  *(uint16_t*)0x20000468 = 0x7fff;
  *(uint16_t*)0x2000046a = 0xf;
  *(uint16_t*)0x2000046c = 0x100;
  *(uint16_t*)0x2000046e = 0x2c5;
  *(uint16_t*)0x20000470 = 7;
  *(uint16_t*)0x20000472 = 5;
  *(uint16_t*)0x20000474 = 6;
  *(uint16_t*)0x20000476 = 0xa;
  *(uint16_t*)0x20000478 = 1;
  *(uint16_t*)0x2000047a = 2;
  *(uint32_t*)0x2000047c = 0;
  *(uint32_t*)0x20000480 = 0xa;
  *(uint32_t*)0x20000484 = 0xa;
  *(uint32_t*)0x20000488 = 4;
  *(uint32_t*)0x2000048c = 8;
  *(uint32_t*)0x20000490 = 0x304d434e;
  *(uint16_t*)0x20000494 = 0x2c;
  *(uint16_t*)0x20000496 = 0x2fc;
  *(uint16_t*)0x20000498 = 6;
  *(uint16_t*)0x2000049a = 0xfbf8;
  *(uint16_t*)0x2000049c = 0xb0;
  *(uint16_t*)0x2000049e = 0xd;
  *(uint16_t*)0x200004a0 = 9;
  *(uint16_t*)0x200004a2 = 0;
  *(uint16_t*)0x200004a4 = 0x5c7;
  *(uint16_t*)0x200004a6 = 0x800;
  *(uint16_t*)0x200004a8 = 8;
  *(uint16_t*)0x200004aa = 2;
  *(uint16_t*)0x200004ac = 0x30d0;
  *(uint16_t*)0x200004ae = 9;
  *(uint16_t*)0x200004b0 = 0xfe06;
  *(uint16_t*)0x200004b2 = 0x13aa;
  *(uint16_t*)0x200004b4 = 8;
  *(uint16_t*)0x200004b6 = 0x80;
  *(uint32_t*)0x200004b8 = 0;
  *(uint32_t*)0x200004bc = 0x9b54;
  *(uint32_t*)0x200004c0 = 0;
  *(uint32_t*)0x200004c4 = 0x304d434e;
  *(uint16_t*)0x200004c8 = 0x10;
  *(uint16_t*)0x200004ca = 0x3b0;
  *(uint16_t*)0x200004cc = 7;
  *(uint16_t*)0x200004ce = 6;
  *(uint32_t*)0x200004d0 = 0;
  *(uint32_t*)0x200004d4 = 4;
  *(uint32_t*)0x200004d8 = 6;
  *(uint32_t*)0x200004dc = 1;
  syz_usb_ncm_send(/*fd=*/r[4], /*pkg=*/0x20000440, /*l=*/0xa0);
  syz_usb_ncm_gadget_setup();
  res = -1;
  res = syz_usb_ncm_gadget_setup();
  if (res != -1)
    r[5] = res;
  memcpy((void*)0x20000500,
         "\x4e\x43\x4d\x48\x0c\x00\x04\x00\xa8\x00\x0c\x00\x4e\x43\x4d\x30\x2c"
         "\x00\x94\x03\x40\x00\x34\x17\x08\x00\x07\x00\x00\x00\x00\x00\x00\x00"
         "\x05\x05\x01\x00\x09\x00\x03\x00\x00\x00\x06\x00\x2d\x00\x00\x20\x00"
         "\x00\x00\x03\x00\x00\x00\x6f\x88\x38\xff\x09\x00\x00\x00\x4e\x43\x4d"
         "\x30\x18\x00\xe4\x00\x00\x01\x08\x00\x00\x00\x07\x00\xfd\xff\x10\x00"
         "\x00\x00\x00\x00\x00\x00\x00\x00\x0e\x00\x00\x00\xbb\x33\x00\x00\x03"
         "\x00\x00\x00\x06\x00\x00\x00\x04\x00\x00\x00\xf7\x04\x00\x00\x01\x00"
         "\x00\x00\x4e\x43\x4d\x30\x18\x00\x9c\x01\xd5\x22\x45\x00\x80\x00\x03"
         "\x00\x01\x01\x50\xff\x00\x20\x00\x00\xff\x03\x00\x00\xff\xff\x00\x00"
         "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
         168);
  syz_usb_ncm_send(/*fd=*/r[5], /*pkg=*/0x20000500, /*l=*/0xa8);
  *(uint32_t*)0x200005c0 = 0x484d434e;
  *(uint16_t*)0x200005c4 = 0xc;
  *(uint16_t*)0x200005c6 = 0xdef;
  *(uint16_t*)0x200005c8 = 0xa0;
  *(uint16_t*)0x200005ca = 0xc;
  *(uint32_t*)0x200005cc = 0x304d434e;
  *(uint16_t*)0x200005d0 = 0x34;
  *(uint16_t*)0x200005d2 = 0x19c;
  *(uint16_t*)0x200005d4 = 7;
  *(uint16_t*)0x200005d6 = 0x79ec;
  *(uint16_t*)0x200005d8 = 3;
  *(uint16_t*)0x200005da = 0x511a;
  *(uint16_t*)0x200005dc = 7;
  *(uint16_t*)0x200005de = 0x1000;
  *(uint16_t*)0x200005e0 = 4;
  *(uint16_t*)0x200005e2 = 7;
  *(uint16_t*)0x200005e4 = 7;
  *(uint16_t*)0x200005e6 = 8;
  *(uint16_t*)0x200005e8 = 0xfe2;
  *(uint16_t*)0x200005ea = 0;
  *(uint16_t*)0x200005ec = 0xd86;
  *(uint16_t*)0x200005ee = 0;
  *(uint16_t*)0x200005f0 = 7;
  *(uint16_t*)0x200005f2 = 0x401;
  *(uint16_t*)0x200005f4 = 8;
  *(uint16_t*)0x200005f6 = 7;
  *(uint16_t*)0x200005f8 = 7;
  *(uint16_t*)0x200005fa = 0x100;
  *(uint32_t*)0x200005fc = 0;
  *(uint32_t*)0x20000600 = 0xfffffff3;
  *(uint32_t*)0x20000604 = 0;
  *(uint32_t*)0x20000608 = 0xffffffcf;
  *(uint32_t*)0x2000060c = 4;
  *(uint32_t*)0x20000610 = 3;
  *(uint32_t*)0x20000614 = 0x304d434e;
  *(uint16_t*)0x20000618 = 0x20;
  *(uint16_t*)0x2000061a = 0x1ac;
  *(uint16_t*)0x2000061c = 5;
  *(uint16_t*)0x2000061e = 0xfff;
  *(uint16_t*)0x20000620 = 2;
  *(uint16_t*)0x20000622 = 7;
  *(uint16_t*)0x20000624 = 6;
  *(uint16_t*)0x20000626 = 0;
  *(uint16_t*)0x20000628 = 8;
  *(uint16_t*)0x2000062a = 8;
  *(uint16_t*)0x2000062c = 0;
  *(uint16_t*)0x2000062e = 0x79;
  *(uint32_t*)0x20000630 = 0;
  *(uint32_t*)0x20000634 = 0x80000001;
  *(uint32_t*)0x20000638 = 0x304d434e;
  *(uint16_t*)0x2000063c = 0x24;
  *(uint16_t*)0x2000063e = 0x98;
  *(uint16_t*)0x20000640 = 4;
  *(uint16_t*)0x20000642 = 9;
  *(uint16_t*)0x20000644 = 8;
  *(uint16_t*)0x20000646 = 0x67;
  *(uint16_t*)0x20000648 = 0x400;
  *(uint16_t*)0x2000064a = 0;
  *(uint16_t*)0x2000064c = 0xff;
  *(uint16_t*)0x2000064e = 6;
  *(uint16_t*)0x20000650 = 6;
  *(uint16_t*)0x20000652 = 5;
  *(uint16_t*)0x20000654 = 0x5000;
  *(uint16_t*)0x20000656 = 0xfff6;
  *(uint32_t*)0x20000658 = 0;
  *(uint32_t*)0x2000065c = 8;
  syz_usb_ncm_send(/*fd=*/r[5], /*pkg=*/0x200005c0, /*l=*/0xa0);
  syz_usb_ncm_gadget_setup();
  res = -1;
  res = syz_usb_ncm_gadget_setup();
  if (res != -1)
    r[6] = res;
  res = -1;
  res = syz_usb_ncm_gadget_setup();
  if (res != -1)
    r[7] = res;
  syz_usb_ncm_gadget_setup();
  *(uint32_t*)0x20000680 = 0x484d434e;
  *(uint16_t*)0x20000684 = 0xc;
  *(uint16_t*)0x20000686 = 5;
  *(uint16_t*)0x20000688 = 0x90;
  *(uint16_t*)0x2000068a = 0xc;
  *(uint32_t*)0x2000068c = 0x304d434e;
  *(uint16_t*)0x20000690 = 0x20;
  *(uint16_t*)0x20000692 = 3;
  *(uint16_t*)0x20000694 = 3;
  *(uint16_t*)0x20000696 = 1;
  *(uint16_t*)0x20000698 = 0xfff;
  *(uint16_t*)0x2000069a = 0xfffd;
  *(uint16_t*)0x2000069c = 0xd;
  *(uint16_t*)0x2000069e = 0x800;
  *(uint16_t*)0x200006a0 = 0x2000;
  *(uint16_t*)0x200006a2 = 3;
  *(uint16_t*)0x200006a4 = 0xb;
  *(uint16_t*)0x200006a6 = 1;
  *(uint32_t*)0x200006a8 = 0;
  *(uint32_t*)0x200006ac = 7;
  *(uint32_t*)0x200006b0 = 8;
  *(uint32_t*)0x200006b4 = -1;
  *(uint32_t*)0x200006b8 = 7;
  *(uint32_t*)0x200006bc = 0x81;
  *(uint32_t*)0x200006c0 = 0x304d434e;
  *(uint16_t*)0x200006c4 = 0x1c;
  *(uint16_t*)0x200006c6 = 0x188;
  *(uint16_t*)0x200006c8 = 5;
  *(uint16_t*)0x200006ca = 0x3ff;
  *(uint16_t*)0x200006cc = 4;
  *(uint16_t*)0x200006ce = 0xfff;
  *(uint16_t*)0x200006d0 = 8;
  *(uint16_t*)0x200006d2 = 0xfffb;
  *(uint16_t*)0x200006d4 = 0xa9c7;
  *(uint16_t*)0x200006d6 = 8;
  *(uint32_t*)0x200006d8 = 0;
  *(uint32_t*)0x200006dc = 0;
  *(uint32_t*)0x200006e0 = 0x304d434e;
  *(uint16_t*)0x200006e4 = 0x14;
  *(uint16_t*)0x200006e6 = 0x2dc;
  *(uint16_t*)0x200006e8 = 2;
  *(uint16_t*)0x200006ea = 6;
  *(uint16_t*)0x200006ec = 9;
  *(uint16_t*)0x200006ee = 0x660b;
  *(uint32_t*)0x200006f0 = 0;
  *(uint32_t*)0x200006f4 = 4;
  *(uint32_t*)0x200006f8 = 0;
  *(uint32_t*)0x200006fc = 0x9ace4776;
  *(uint32_t*)0x20000700 = 0x9a36;
  *(uint32_t*)0x20000704 = 0;
  *(uint32_t*)0x20000708 = 0x100;
  *(uint32_t*)0x2000070c = 0;
  syz_usb_ncm_send(/*fd=*/r[2], /*pkg=*/0x20000680, /*l=*/0x90);
  res = -1;
  res = syz_usb_ncm_gadget_setup();
  if (res != -1)
    r[8] = res;
  *(uint32_t*)0x20000740 = 0x484d434e;
  *(uint16_t*)0x20000744 = 0xc;
  *(uint16_t*)0x20000746 = 3;
  *(uint16_t*)0x20000748 = 0xb0;
  *(uint16_t*)0x2000074a = 0xc;
  *(uint32_t*)0x2000074c = 0x304d434e;
  *(uint16_t*)0x20000750 = 0x18;
  *(uint16_t*)0x20000752 = 0xe4;
  *(uint16_t*)0x20000754 = 0x400;
  *(uint16_t*)0x20000756 = 2;
  *(uint16_t*)0x20000758 = 4;
  *(uint16_t*)0x2000075a = 8;
  *(uint16_t*)0x2000075c = 4;
  *(uint16_t*)0x2000075e = 0x71;
  *(uint32_t*)0x20000760 = 0;
  *(uint32_t*)0x20000764 = 7;
  *(uint32_t*)0x20000768 = 0xc522;
  *(uint32_t*)0x2000076c = 0x10;
  *(uint32_t*)0x20000770 = 0x304d434e;
  *(uint16_t*)0x20000774 = 0x28;
  *(uint16_t*)0x20000776 = 0x370;
  *(uint16_t*)0x20000778 = 8;
  *(uint16_t*)0x2000077a = 0x200;
  *(uint16_t*)0x2000077c = 0x250a;
  *(uint16_t*)0x2000077e = 0xffa3;
  *(uint16_t*)0x20000780 = 7;
  *(uint16_t*)0x20000782 = 7;
  *(uint16_t*)0x20000784 = 0;
  *(uint16_t*)0x20000786 = 5;
  *(uint16_t*)0x20000788 = 2;
  *(uint16_t*)0x2000078a = 2;
  *(uint16_t*)0x2000078c = 1;
  *(uint16_t*)0x2000078e = 7;
  *(uint16_t*)0x20000790 = 7;
  *(uint16_t*)0x20000792 = 0x7f;
  *(uint32_t*)0x20000794 = 0;
  *(uint32_t*)0x20000798 = 5;
  *(uint32_t*)0x2000079c = 0;
  *(uint32_t*)0x200007a0 = 0x91b8;
  *(uint32_t*)0x200007a4 = 0xffff7c54;
  *(uint32_t*)0x200007a8 = 4;
  *(uint32_t*)0x200007ac = 0x41;
  *(uint32_t*)0x200007b0 = 0x304d434e;
  *(uint16_t*)0x200007b4 = 0x24;
  *(uint16_t*)0x200007b6 = 0x400;
  *(uint16_t*)0x200007b8 = 0;
  *(uint16_t*)0x200007ba = 0x98;
  *(uint16_t*)0x200007bc = 8;
  *(uint16_t*)0x200007be = 6;
  *(uint16_t*)0x200007c0 = 4;
  *(uint16_t*)0x200007c2 = 0x3ff;
  *(uint16_t*)0x200007c4 = 0xd5c;
  *(uint16_t*)0x200007c6 = 0;
  *(uint16_t*)0x200007c8 = 3;
  *(uint16_t*)0x200007ca = 0xfffb;
  *(uint16_t*)0x200007cc = 2;
  *(uint16_t*)0x200007ce = 4;
  *(uint32_t*)0x200007d0 = 0;
  *(uint32_t*)0x200007d4 = 0xd534;
  *(uint32_t*)0x200007d8 = 6;
  *(uint32_t*)0x200007dc = 9;
  *(uint32_t*)0x200007e0 = 0x3ff;
  *(uint32_t*)0x200007e4 = 5;
  *(uint32_t*)0x200007e8 = 0x1ff;
  *(uint32_t*)0x200007ec = 5;
  syz_usb_ncm_send(/*fd=*/r[6], /*pkg=*/0x20000740, /*l=*/0xb0);
  *(uint32_t*)0x20000800 = 0x484d434e;
  *(uint16_t*)0x20000804 = 0xc;
  *(uint16_t*)0x20000806 = 0;
  *(uint16_t*)0x20000808 = 0x90;
  *(uint16_t*)0x2000080a = 0xc;
  *(uint32_t*)0x2000080c = 0x304d434e;
  *(uint16_t*)0x20000810 = 0x10;
  *(uint16_t*)0x20000812 = 0xb8;
  *(uint16_t*)0x20000814 = 8;
  *(uint16_t*)0x20000816 = 9;
  *(uint32_t*)0x20000818 = 0;
  *(uint32_t*)0x2000081c = 6;
  *(uint32_t*)0x20000820 = 0x304d434e;
  *(uint16_t*)0x20000824 = 0x1c;
  *(uint16_t*)0x20000826 = 0x2a4;
  *(uint16_t*)0x20000828 = 0x1ff;
  *(uint16_t*)0x2000082a = 0;
  *(uint16_t*)0x2000082c = 5;
  *(uint16_t*)0x2000082e = 0x401;
  *(uint16_t*)0x20000830 = 5;
  *(uint16_t*)0x20000832 = 0x2c;
  *(uint16_t*)0x20000834 = 9;
  *(uint16_t*)0x20000836 = 0x8000;
  *(uint32_t*)0x20000838 = 0;
  *(uint32_t*)0x2000083c = 0x10001;
  *(uint32_t*)0x20000840 = 5;
  *(uint32_t*)0x20000844 = 2;
  *(uint32_t*)0x20000848 = 0x800;
  *(uint32_t*)0x2000084c = 7;
  *(uint32_t*)0x20000850 = 0x65;
  *(uint32_t*)0x20000854 = 1;
  *(uint32_t*)0x20000858 = 4;
  *(uint32_t*)0x2000085c = 5;
  *(uint32_t*)0x20000860 = 0x304d434e;
  *(uint16_t*)0x20000864 = 0x18;
  *(uint16_t*)0x20000866 = 0x358;
  *(uint16_t*)0x20000868 = 9;
  *(uint16_t*)0x2000086a = 3;
  *(uint16_t*)0x2000086c = 7;
  *(uint16_t*)0x2000086e = -1;
  *(uint16_t*)0x20000870 = 8;
  *(uint16_t*)0x20000872 = 0xf2a9;
  *(uint32_t*)0x20000874 = 0;
  *(uint32_t*)0x20000878 = 7;
  *(uint32_t*)0x2000087c = 8;
  *(uint32_t*)0x20000880 = 3;
  *(uint32_t*)0x20000884 = 0x1000;
  *(uint32_t*)0x20000888 = 7;
  *(uint32_t*)0x2000088c = 8;
  syz_usb_ncm_send(/*fd=*/r[7], /*pkg=*/0x20000800, /*l=*/0x90);
  *(uint32_t*)0x200008c0 = 0x484d434e;
  *(uint16_t*)0x200008c4 = 0xc;
  *(uint16_t*)0x200008c6 = 9;
  *(uint16_t*)0x200008c8 = 0x98;
  *(uint16_t*)0x200008ca = 0xc;
  *(uint32_t*)0x200008cc = 0x304d434e;
  *(uint16_t*)0x200008d0 = 0x18;
  *(uint16_t*)0x200008d2 = 0x84;
  *(uint16_t*)0x200008d4 = 0x8001;
  *(uint16_t*)0x200008d6 = 3;
  *(uint16_t*)0x200008d8 = 6;
  *(uint16_t*)0x200008da = 7;
  *(uint16_t*)0x200008dc = 6;
  *(uint16_t*)0x200008de = 6;
  *(uint32_t*)0x200008e0 = 0;
  *(uint32_t*)0x200008e4 = 0x81;
  *(uint32_t*)0x200008e8 = 0;
  *(uint32_t*)0x200008ec = 2;
  *(uint32_t*)0x200008f0 = 3;
  *(uint32_t*)0x200008f4 = 5;
  *(uint32_t*)0x200008f8 = 9;
  *(uint32_t*)0x200008fc = 0x80000000;
  *(uint32_t*)0x20000900 = -1;
  *(uint32_t*)0x20000904 = 0x304d434e;
  *(uint16_t*)0x20000908 = 0x2c;
  *(uint16_t*)0x2000090a = 0x388;
  *(uint16_t*)0x2000090c = 6;
  *(uint16_t*)0x2000090e = 0x5b12;
  *(uint16_t*)0x20000910 = 0xe;
  *(uint16_t*)0x20000912 = 6;
  *(uint16_t*)0x20000914 = 0xfff9;
  *(uint16_t*)0x20000916 = 0x10;
  *(uint16_t*)0x20000918 = 8;
  *(uint16_t*)0x2000091a = 0x53b5;
  *(uint16_t*)0x2000091c = 0x600;
  *(uint16_t*)0x2000091e = 0x608;
  *(uint16_t*)0x20000920 = 0xff;
  *(uint16_t*)0x20000922 = 2;
  *(uint16_t*)0x20000924 = 0x400;
  *(uint16_t*)0x20000926 = 9;
  *(uint16_t*)0x20000928 = 0x5ed2;
  *(uint16_t*)0x2000092a = 1;
  *(uint32_t*)0x2000092c = 0;
  *(uint32_t*)0x20000930 = 5;
  *(uint32_t*)0x20000934 = 0xc483;
  *(uint32_t*)0x20000938 = 9;
  *(uint32_t*)0x2000093c = 7;
  *(uint32_t*)0x20000940 = 0x304d434e;
  *(uint16_t*)0x20000944 = 0xc;
  *(uint16_t*)0x20000946 = 0x388;
  *(uint32_t*)0x20000948 = 0;
  *(uint32_t*)0x2000094c = 4;
  *(uint32_t*)0x20000950 = 8;
  *(uint32_t*)0x20000954 = 8;
  syz_usb_ncm_send(/*fd=*/r[5], /*pkg=*/0x200008c0, /*l=*/0x98);
  *(uint32_t*)0x20000980 = 0x484d434e;
  *(uint16_t*)0x20000984 = 0xc;
  *(uint16_t*)0x20000986 = 3;
  *(uint16_t*)0x20000988 = 0x8c;
  *(uint16_t*)0x2000098a = 0xc;
  *(uint32_t*)0x2000098c = 0x304d434e;
  *(uint16_t*)0x20000990 = 0x10;
  *(uint16_t*)0x20000992 = 0x1e8;
  *(uint16_t*)0x20000994 = 0x977;
  *(uint16_t*)0x20000996 = 0x79;
  *(uint32_t*)0x20000998 = 0;
  *(uint32_t*)0x2000099c = 0x42;
  *(uint32_t*)0x200009a0 = 9;
  *(uint32_t*)0x200009a4 = 0xfff;
  *(uint32_t*)0x200009a8 = 6;
  *(uint32_t*)0x200009ac = 4;
  *(uint32_t*)0x200009b0 = 3;
  *(uint32_t*)0x200009b4 = 0x304d434e;
  *(uint16_t*)0x200009b8 = 0x28;
  *(uint16_t*)0x200009ba = 0x3e8;
  *(uint16_t*)0x200009bc = 3;
  *(uint16_t*)0x200009be = 1;
  *(uint16_t*)0x200009c0 = 4;
  *(uint16_t*)0x200009c2 = 0xa34;
  *(uint16_t*)0x200009c4 = 2;
  *(uint16_t*)0x200009c6 = 9;
  *(uint16_t*)0x200009c8 = 5;
  *(uint16_t*)0x200009ca = 0;
  *(uint16_t*)0x200009cc = 0x7fff;
  *(uint16_t*)0x200009ce = 0xa2a5;
  *(uint16_t*)0x200009d0 = 0x31;
  *(uint16_t*)0x200009d2 = 0x400;
  *(uint16_t*)0x200009d4 = 0;
  *(uint16_t*)0x200009d6 = 0;
  *(uint32_t*)0x200009d8 = 0;
  *(uint32_t*)0x200009dc = 1;
  *(uint32_t*)0x200009e0 = 4;
  *(uint32_t*)0x200009e4 = 0xc;
  *(uint32_t*)0x200009e8 = 0x304d434e;
  *(uint16_t*)0x200009ec = 0x20;
  *(uint16_t*)0x200009ee = 0xf;
  *(uint16_t*)0x200009f0 = 0xf;
  *(uint16_t*)0x200009f2 = 7;
  *(uint16_t*)0x200009f4 = 2;
  *(uint16_t*)0x200009f6 = 2;
  *(uint16_t*)0x200009f8 = 0x1000;
  *(uint16_t*)0x200009fa = 0xb56d;
  *(uint16_t*)0x200009fc = 0xbbf;
  *(uint16_t*)0x200009fe = 7;
  *(uint16_t*)0x20000a00 = 0xd9;
  *(uint16_t*)0x20000a02 = 0xfff7;
  *(uint32_t*)0x20000a04 = 0;
  *(uint32_t*)0x20000a08 = 0;
  syz_usb_ncm_send(/*fd=*/r[1], /*pkg=*/0x20000980, /*l=*/0x8c);
  *(uint32_t*)0x20000a40 = 0x484d434e;
  *(uint16_t*)0x20000a44 = 0xc;
  *(uint16_t*)0x20000a46 = 1;
  *(uint16_t*)0x20000a48 = 0x88;
  *(uint16_t*)0x20000a4a = 0xc;
  *(uint32_t*)0x20000a4c = 0x304d434e;
  *(uint16_t*)0x20000a50 = 0x10;
  *(uint16_t*)0x20000a52 = 0x2cc;
  *(uint16_t*)0x20000a54 = 6;
  *(uint16_t*)0x20000a56 = 2;
  *(uint32_t*)0x20000a58 = 0;
  *(uint32_t*)0x20000a5c = 0;
  *(uint32_t*)0x20000a60 = 5;
  *(uint32_t*)0x20000a64 = 0xa9f;
  *(uint32_t*)0x20000a68 = 0x28000;
  *(uint32_t*)0x20000a6c = 0x304d434e;
  *(uint16_t*)0x20000a70 = 0x14;
  *(uint16_t*)0x20000a72 = 0x374;
  *(uint16_t*)0x20000a74 = 4;
  *(uint16_t*)0x20000a76 = 0xd;
  *(uint16_t*)0x20000a78 = 0xa;
  *(uint16_t*)0x20000a7a = 5;
  *(uint32_t*)0x20000a7c = 0;
  *(uint32_t*)0x20000a80 = 0xee16;
  *(uint32_t*)0x20000a84 = 0xb6;
  *(uint32_t*)0x20000a88 = 1;
  *(uint32_t*)0x20000a8c = 2;
  *(uint32_t*)0x20000a90 = 0x101;
  *(uint32_t*)0x20000a94 = 4;
  *(uint32_t*)0x20000a98 = 0x5342;
  *(uint32_t*)0x20000a9c = 7;
  *(uint32_t*)0x20000aa0 = 0x304d434e;
  *(uint16_t*)0x20000aa4 = 0x14;
  *(uint16_t*)0x20000aa6 = 0x3e4;
  *(uint16_t*)0x20000aa8 = 0x7f;
  *(uint16_t*)0x20000aaa = 0xc;
  *(uint16_t*)0x20000aac = 0x80;
  *(uint16_t*)0x20000aae = 4;
  *(uint32_t*)0x20000ab0 = 0;
  *(uint32_t*)0x20000ab4 = 0xfff;
  *(uint32_t*)0x20000ab8 = 3;
  *(uint32_t*)0x20000abc = 0x7fff;
  *(uint32_t*)0x20000ac0 = 0xffff;
  *(uint32_t*)0x20000ac4 = 5;
  syz_usb_ncm_send(/*fd=*/r[8], /*pkg=*/0x20000a40, /*l=*/0x88);
  *(uint32_t*)0x20000b00 = 0x484d434e;
  *(uint16_t*)0x20000b04 = 0xc;
  *(uint16_t*)0x20000b06 = 1;
  *(uint16_t*)0x20000b08 = 0xa8;
  *(uint16_t*)0x20000b0a = 0xc;
  *(uint32_t*)0x20000b0c = 0x304d434e;
  *(uint16_t*)0x20000b10 = 0x20;
  *(uint16_t*)0x20000b12 = 0x2d0;
  *(uint16_t*)0x20000b14 = 0xa93;
  *(uint16_t*)0x20000b16 = 0xd4;
  *(uint16_t*)0x20000b18 = 0xfff9;
  *(uint16_t*)0x20000b1a = 8;
  *(uint16_t*)0x20000b1c = 8;
  *(uint16_t*)0x20000b1e = 4;
  *(uint16_t*)0x20000b20 = 0x7f;
  *(uint16_t*)0x20000b22 = 0x10;
  *(uint16_t*)0x20000b24 = 4;
  *(uint16_t*)0x20000b26 = 5;
  *(uint32_t*)0x20000b28 = 0;
  *(uint32_t*)0x20000b2c = 5;
  *(uint32_t*)0x20000b30 = 3;
  *(uint32_t*)0x20000b34 = 2;
  *(uint32_t*)0x20000b38 = 0xbc0c;
  *(uint32_t*)0x20000b3c = 2;
  *(uint32_t*)0x20000b40 = 9;
  *(uint32_t*)0x20000b44 = 0x304d434e;
  *(uint16_t*)0x20000b48 = 0x10;
  *(uint16_t*)0x20000b4a = 0x344;
  *(uint16_t*)0x20000b4c = 4;
  *(uint16_t*)0x20000b4e = 0xfffa;
  *(uint32_t*)0x20000b50 = 0;
  *(uint32_t*)0x20000b54 = 0xde8;
  *(uint32_t*)0x20000b58 = 2;
  *(uint32_t*)0x20000b5c = 7;
  *(uint32_t*)0x20000b60 = 0xfffffff7;
  *(uint32_t*)0x20000b64 = 3;
  *(uint32_t*)0x20000b68 = 4;
  *(uint32_t*)0x20000b6c = 0x304d434e;
  *(uint16_t*)0x20000b70 = 0x24;
  *(uint16_t*)0x20000b72 = 0x2ec;
  *(uint16_t*)0x20000b74 = 5;
  *(uint16_t*)0x20000b76 = 1;
  *(uint16_t*)0x20000b78 = 0;
  *(uint16_t*)0x20000b7a = 0x451;
  *(uint16_t*)0x20000b7c = 9;
  *(uint16_t*)0x20000b7e = 1;
  *(uint16_t*)0x20000b80 = 0x5277;
  *(uint16_t*)0x20000b82 = 3;
  *(uint16_t*)0x20000b84 = 3;
  *(uint16_t*)0x20000b86 = 1;
  *(uint16_t*)0x20000b88 = 5;
  *(uint16_t*)0x20000b8a = 0;
  *(uint32_t*)0x20000b8c = 0;
  *(uint32_t*)0x20000b90 = 7;
  *(uint32_t*)0x20000b94 = 4;
  *(uint32_t*)0x20000b98 = 0xceae;
  *(uint32_t*)0x20000b9c = 0x8d1;
  *(uint32_t*)0x20000ba0 = 0;
  *(uint32_t*)0x20000ba4 = 7;
  syz_usb_ncm_send(/*fd=*/r[2], /*pkg=*/0x20000b00, /*l=*/0xa8);
  *(uint32_t*)0x20000bc0 = 0x484d434e;
  *(uint16_t*)0x20000bc4 = 0xc;
  *(uint16_t*)0x20000bc6 = 0xd96b;
  *(uint16_t*)0x20000bc8 = 0xbc;
  *(uint16_t*)0x20000bca = 0xc;
  *(uint32_t*)0x20000bcc = 0x304d434e;
  *(uint16_t*)0x20000bd0 = 0x1c;
  *(uint16_t*)0x20000bd2 = 0x80;
  *(uint16_t*)0x20000bd4 = 9;
  *(uint16_t*)0x20000bd6 = 6;
  *(uint16_t*)0x20000bd8 = 0xfff2;
  *(uint16_t*)0x20000bda = 8;
  *(uint16_t*)0x20000bdc = 6;
  *(uint16_t*)0x20000bde = 0x100;
  *(uint16_t*)0x20000be0 = 2;
  *(uint16_t*)0x20000be2 = 0xfff7;
  *(uint32_t*)0x20000be4 = 0;
  *(uint32_t*)0x20000be8 = 5;
  *(uint32_t*)0x20000bec = 5;
  *(uint32_t*)0x20000bf0 = 1;
  *(uint32_t*)0x20000bf4 = 4;
  *(uint32_t*)0x20000bf8 = 0x7fff;
  *(uint32_t*)0x20000bfc = 0x304d434e;
  *(uint16_t*)0x20000c00 = 0x2c;
  *(uint16_t*)0x20000c02 = 0x58;
  *(uint16_t*)0x20000c04 = 6;
  *(uint16_t*)0x20000c06 = 0xc43;
  *(uint16_t*)0x20000c08 = 5;
  *(uint16_t*)0x20000c0a = 4;
  *(uint16_t*)0x20000c0c = 3;
  *(uint16_t*)0x20000c0e = 1;
  *(uint16_t*)0x20000c10 = 6;
  *(uint16_t*)0x20000c12 = 9;
  *(uint16_t*)0x20000c14 = 0xf089;
  *(uint16_t*)0x20000c16 = 0x43d;
  *(uint16_t*)0x20000c18 = 6;
  *(uint16_t*)0x20000c1a = 0x1000;
  *(uint16_t*)0x20000c1c = 0xb;
  *(uint16_t*)0x20000c1e = 5;
  *(uint16_t*)0x20000c20 = 0xfffd;
  *(uint16_t*)0x20000c22 = 0x15;
  *(uint32_t*)0x20000c24 = 0;
  *(uint32_t*)0x20000c28 = 0x10001;
  *(uint32_t*)0x20000c2c = 0xeb;
  *(uint32_t*)0x20000c30 = 0x40;
  *(uint32_t*)0x20000c34 = 3;
  *(uint32_t*)0x20000c38 = 0x7ff;
  *(uint32_t*)0x20000c3c = 0x10001;
  *(uint32_t*)0x20000c40 = 0x304d434e;
  *(uint16_t*)0x20000c44 = 0x34;
  *(uint16_t*)0x20000c46 = 0x2c8;
  *(uint16_t*)0x20000c48 = 0xa4;
  *(uint16_t*)0x20000c4a = 5;
  *(uint16_t*)0x20000c4c = 5;
  *(uint16_t*)0x20000c4e = 5;
  *(uint16_t*)0x20000c50 = 0x7fff;
  *(uint16_t*)0x20000c52 = 3;
  *(uint16_t*)0x20000c54 = 4;
  *(uint16_t*)0x20000c56 = 0x25;
  *(uint16_t*)0x20000c58 = 0;
  *(uint16_t*)0x20000c5a = 0x8379;
  *(uint16_t*)0x20000c5c = 9;
  *(uint16_t*)0x20000c5e = 8;
  *(uint16_t*)0x20000c60 = 2;
  *(uint16_t*)0x20000c62 = 0x1a0;
  *(uint16_t*)0x20000c64 = 0;
  *(uint16_t*)0x20000c66 = 1;
  *(uint16_t*)0x20000c68 = 0xe2a;
  *(uint16_t*)0x20000c6a = 6;
  *(uint16_t*)0x20000c6c = 0x7f;
  *(uint16_t*)0x20000c6e = 4;
  *(uint32_t*)0x20000c70 = 0;
  *(uint32_t*)0x20000c74 = 4;
  *(uint32_t*)0x20000c78 = 4;
  syz_usb_ncm_send(/*fd=*/r[7], /*pkg=*/0x20000bc0, /*l=*/0xbc);
  syz_usb_ncm_gadget_setup();
}

const char usage[] = "usage: reproducer <bus_num> <device_num> <ep_num>\n";

int main(int argc, char **argv)
{
  int bus, dev;
  if (argc < 4) {
    write(1, usage, sizeof(usage));
    return -1;
  }
  bus = atoi(argv[1]);
  dev = atoi(argv[2]);
  ep = atoi(argv[3]);
  snprintf(bus_path, sizeof(bus_path), "/dev/bus/usb/%03d/%03d", bus, dev);
  syscall(__NR_mmap, /*addr=*/0x1ffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x20000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x21000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  const char* reason;
  (void)reason;
  loop();
  return 0;
}
